# Generated by Django 5.0.6 on 2024-05-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance_nf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissor',
            options={'verbose_name': 'Emissor', 'verbose_name_plural': 'Emissores'},
        ),
        migrations.AlterField(
            model_name='data',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
