# Generated by Django 4.2.13 on 2024-05-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuance_nf', '0002_alter_emissor_options_alter_data_data_emissao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='NotaFiscal',
        ),
    ]
